
version: '3.7'

services:

  app:
    build: .
    command: ["sh", "start.sh"]
    volumes:
      - .:/usr/src/activity/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.docker-compose

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=activity
      - POSTGRES_PASSWORD=activity
      - POSTGRES_DB=activity_dev
    ports:
      - 5432:5432

volumes:
  postgres_data:
