version: '3.7'

services:
  web:
    build: ./activity_ce
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./activity_ce:/root/Downloads/django-on-docker/activity_ce
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

volumes:
  postgres_data:
