name: Activity

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  Build_lint_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics # TODO use a main flake8 config file
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Tests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        cp activity/settings/local-sample.py activity/settings/local.py
        pip install pip-tools && pip-sync
        coverage run manage.py test
        echo "++++++++ Show test coverage report +++++++"
        coverage report
        echo "----------- Upload test coverage ---------"
        bash <(curl -s https://codecov.io/bash)
